on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: trigger target workflow
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.PAT_TOKEN}}
          script: |
            const result = await github.rest.repos.createDispatchEvent({
            owner: 'LiQunXia',
            repo: 'liqun.xia.github.io',
            event_type: 'test_upload'
            })
            console.log(result);
